// Command vbrunprops regenerates pkg/vbx/vbrun_tables.go from VBRUN300.DLL.
//
// VBRUN300.DLL implements the standard VB3 controls with the same MODEL and
// PROPINFO structures used by custom controls. This tool locates the standard
// property table (the targets of the ~0..~42 sentinels) and the built-in
// control models in the runtime's data segment and emits them as Go source:
//
//	go run ./cmd/vbrunprops test_input/ff/VBRUN300.DLL > pkg/vbx/vbrun_tables.go
package main

import (
	"encoding/binary"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"vb3dec/pkg/ne"
	"vb3dec/pkg/vbx"
)

// stdCount is the number of standard properties (PPROPINFO_STD_* sentinels).
const stdCount = 43

// stdAnchor is the documented CDK order of the first standard properties.
var stdAnchor = []string{
	"Name", "Index", "hWnd", "BackColor", "ForeColor", "Left", "Top", "Width",
	"Height", "Enabled", "Visible", "MousePointer", "Caption", "FontName",
}

// builtinDefNames are the default control names of the VB3 built-in models.
var builtinDefNames = map[string]bool{
	"Check": true, "Combo": true, "Command": true, "Data": true, "Dir": true,
	"Drive": true, "File": true, "Form": true, "Frame": true, "HScroll": true,
	"Image": true, "Label": true, "Line": true, "List": true, "MDIForm": true,
	"Menu": true, "Option": true, "Picture": true, "Shape": true, "Text": true,
	"Timer": true, "VScroll": true,
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: vbrunprops <path-to-VBRUN300.DLL>")
		os.Exit(2)
	}
	f, err := ne.Open(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "opening %s: %v\n", os.Args[1], err)
		os.Exit(1)
	}

	var std []vbx.Prop
	// Other runtime structures also reference the default control names, so
	// keep the candidate with the longest property list for each name.
	byName := make(map[string]*vbx.Model)
	for i := range f.Segments {
		seg := &f.Segments[i]
		if seg.Flags&ne.SegFlagData == 0 || seg.FileLength == 0 {
			continue
		}
		data, err := f.ReadSegmentData(seg)
		if err != nil {
			continue
		}
		if s, ok := findStdTable(data); ok {
			std = s
			for _, m := range vbx.ScanSegment(data, std, false) {
				if !builtinDefNames[m.DefCtlName] {
					continue
				}
				if prev, ok := byName[m.DefCtlName]; !ok || len(m.Props) > len(prev.Props) {
					byName[m.DefCtlName] = m
				}
			}
			break
		}
	}
	if std == nil {
		fmt.Fprintln(os.Stderr, "standard property table not found")
		os.Exit(1)
	}

	models := make([]*vbx.Model, 0, len(byName))
	for _, m := range byName {
		models = append(models, m)
	}
	sort.Slice(models, func(i, j int) bool { return models[i].DefCtlName < models[j].DefCtlName })
	if err := emit(os.Stdout, std, models); err != nil {
		fmt.Fprintf(os.Stderr, "writing output: %v\n", err)
		os.Exit(1)
	}
}

// findStdTable locates the array of stdCount PROPINFO pointers whose names
// begin with the documented standard property order.
func findStdTable(seg []byte) ([]vbx.Prop, bool) {
	for off := 0; off+stdCount*2 <= len(seg); off++ {
		props := make([]vbx.Prop, 0, stdCount)
		for i := 0; i < stdCount; i++ {
			ref := binary.LittleEndian.Uint16(seg[off+i*2:])
			p, ok := vbx.PropInfoAt(seg, ref)
			if !ok {
				p = vbx.Prop{Flags: 0}
			}
			if i < len(stdAnchor) && p.Name != stdAnchor[i] {
				props = nil
				break
			}
			p.Std = i
			props = append(props, p)
		}
		if props != nil {
			return props, true
		}
	}
	return nil, false
}

func emit(w *os.File, std []vbx.Prop, models []*vbx.Model) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/vbrunprops from VBRUN300.DLL; DO NOT EDIT.\n\n")
	sb.WriteString("package vbx\n\n")
	sb.WriteString("// StdProps lists the standard properties referenced by the ~n sentinels in\n")
	sb.WriteString("// control property lists, indexed by n.\n")
	sb.WriteString("var StdProps = []Prop{\n")
	for _, p := range std {
		fmt.Fprintf(&sb, "\t{Name: %q, Flags: 0x%08X, Std: %d},\n", p.Name, p.Flags, p.Std)
	}
	sb.WriteString("}\n\n")
	sb.WriteString("// BuiltinModels lists the control models implemented by VBRUN300.DLL, keyed by\n")
	sb.WriteString("// default control name. Property order is property ID order.\n")
	sb.WriteString("var BuiltinModels = map[string]*Model{\n")
	for _, m := range models {
		fmt.Fprintf(&sb, "\t%q: {DefCtlName: %q, Props: []Prop{\n", m.DefCtlName, m.DefCtlName)
		for i, p := range m.Props {
			fmt.Fprintf(&sb, "\t\t{Name: %q, Flags: 0x%08X, Std: %d}, // 0x%02X\n", p.Name, p.Flags, p.Std, i)
		}
		sb.WriteString("\t}},\n")
	}
	sb.WriteString("}\n")
	src, err := format.Source([]byte(sb.String()))
	if err != nil {
		return err
	}
	_, err = w.Write(src)
	return err
}
