// Code generated by cmd/vbrunprops from VBRUN300.DLL; DO NOT EDIT.

package vbx

// StdProps lists the standard properties referenced by the ~n sentinels in
// control property lists, indexed by n.
var StdProps = []Prop{
	{Name: "Name", Flags: 0x8600D43E, Std: 0},
	{Name: "Index", Flags: 0x84C1D43D, Std: 1},
	{Name: "hWnd", Flags: 0x80005802, Std: 2},
	{Name: "BackColor", Flags: 0x80D12605, Std: 3},
	{Name: "ForeColor", Flags: 0x80D12405, Std: 4},
	{Name: "Left", Flags: 0x90022408, Std: 5},
	{Name: "Top", Flags: 0x9000240A, Std: 6},
	{Name: "Width", Flags: 0x90002409, Std: 7},
	{Name: "Height", Flags: 0x9000240B, Std: 8},
	{Name: "Enabled", Flags: 0x80C14404, Std: 9},
	{Name: "Visible", Flags: 0x80C14404, Std: 10},
	{Name: "MousePointer", Flags: 0x80C12406, Std: 11},
	{Name: "Caption", Flags: 0x80CA4401, Std: 12},
	{Name: "FontName", Flags: 0x90024401, Std: 13},
	{Name: "FontBold", Flags: 0x90004404, Std: 14},
	{Name: "FontItalic", Flags: 0x90004404, Std: 15},
	{Name: "FontStrikethru", Flags: 0x90004404, Std: 16},
	{Name: "FontUnderline", Flags: 0x90004404, Std: 17},
	{Name: "FontSize", Flags: 0x90104407, Std: 18},
	{Name: "TabIndex", Flags: 0x84014402, Std: 19},
	{Name: "Parent", Flags: 0x8000583F, Std: 20},
	{Name: "DragMode", Flags: 0x80C12206, Std: 21},
	{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},
	{Name: "BorderStyle", Flags: 0x80C14406, Std: 23},
	{Name: "TabStop", Flags: 0x80C14404, Std: 24},
	{Name: "Tag", Flags: 0x80C12201, Std: 25},
	{Name: "Name", Flags: 0x8600D43E, Std: 26},
	{Name: "Text", Flags: 0x80CA4401, Std: 27},
	{Name: "BorderStyle", Flags: 0x80C14406, Std: 28},
	{Name: "ClipControls", Flags: 0x80E13204, Std: 29},
	{Name: " ", Flags: 0x40000804, Std: 30},
	{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},
	{Name: "LinkMode", Flags: 0x80C1A406, Std: 32},
	{Name: "LinkItem", Flags: 0x80C1A401, Std: 33},
	{Name: "LinkTopic", Flags: 0x80C1A401, Std: 34},
	{Name: "LinkTimeout", Flags: 0x80C12202, Std: 35},
	{Name: "Left", Flags: 0x82013408, Std: 36},
	{Name: "Top", Flags: 0x8201340A, Std: 37},
	{Name: "Align", Flags: 0x80C12406, Std: 38},
	{Name: " ", Flags: 0xA0C11806, Std: 39},
	{Name: "DataSource", Flags: 0x82D13201, Std: 40},
	{Name: "DataField", Flags: 0x80D12601, Std: 41},
	{Name: "DataChanged", Flags: 0x80102A04, Std: 42},
}

// StdEvents lists the standard events referenced by the ~n sentinels in
// control event lists, indexed by n.
var StdEvents = []Event{
	{Name: "Click", Params: 0, Std: 0},
	{Name: "DblClick", Params: 0, Std: 1},
	{Name: "DragDrop", Params: 3, Std: 2},
	{Name: "DragOver", Params: 4, Std: 3},
	{Name: "GotFocus", Params: 0, Std: 4},
	{Name: "KeyDown", Params: 2, Std: 5},
	{Name: "KeyPress", Params: 1, Std: 6},
	{Name: "KeyUp", Params: 2, Std: 7},
	{Name: "LostFocus", Params: 0, Std: 8},
	{Name: "MouseDown", Params: 4, Std: 9},
	{Name: "MouseMove", Params: 4, Std: 10},
	{Name: "MouseUp", Params: 4, Std: 11},
	{Name: "LinkError", Params: 1, Std: 12},
	{Name: "LinkOpen", Params: 1, Std: 13},
	{Name: "LinkClose", Params: 0, Std: 14},
	{Name: "LinkNotify", Params: 0, Std: 15},
	{Name: "Change", Params: 0, Std: 16},
}

// BuiltinModels lists the control models implemented by VBRUN300.DLL, keyed by
// default control name. Property order is property ID order; event order
// is the slot order of form event tables.
var BuiltinModels = map[string]*Model{
	"Check": {DefCtlName: "Check", Props: []Prop{
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},        // 0x00
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x01
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x02
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x03
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x04
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x05
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x06
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x07
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x08
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x09
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x0A
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0C
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0D
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0E
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x0F
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x10
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x11
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x12
		{Name: "Value", Flags: 0x00C14406, Std: -1},          // 0x13
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x14
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x15
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x16
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x17
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x18
		{Name: "Alignment", Flags: 0x00E13406, Std: -1},      // 0x19
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x1A
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x1B
		{Name: "DataSource", Flags: 0x82D13201, Std: 40},     // 0x1C
		{Name: "DataField", Flags: 0x80D12601, Std: 41},      // 0x1D
		{Name: "DataChanged", Flags: 0x80102A04, Std: 42},    // 0x1E
	}, Events: []Event{
		{Name: "Click", Params: 0, Std: -1},     // slot 0
		{Name: "DragDrop", Params: 3, Std: 2},   // slot 1
		{Name: "DragOver", Params: 4, Std: 3},   // slot 2
		{Name: "GotFocus", Params: 0, Std: 4},   // slot 3
		{Name: "KeyDown", Params: 2, Std: 5},    // slot 4
		{Name: "KeyPress", Params: 1, Std: 6},   // slot 5
		{Name: "KeyUp", Params: 2, Std: 7},      // slot 6
		{Name: "LostFocus", Params: 0, Std: 8},  // slot 7
		{Name: "MouseDown", Params: 4, Std: 9},  // slot 8
		{Name: "MouseMove", Params: 4, Std: 10}, // slot 9
		{Name: "MouseUp", Params: 4, Std: 11},   // slot 10
	}},
	"Combo": {DefCtlName: "Combo", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x01
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x02
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x07
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x08
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x09
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0A
		{Name: "Text", Flags: 0x80CA4401, Std: 27},           // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0C
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0D
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0E
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x0F
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x10
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x11
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x12
		{Name: "ListCount", Flags: 0x00005802, Std: -1},      // 0x13
		{Name: "ListIndex", Flags: 0x00004C02, Std: -1},      // 0x14
		{Name: "List", Flags: 0x00004D01, Std: -1},           // 0x15
		{Name: "Sorted", Flags: 0x00E13204, Std: -1},         // 0x16
		{Name: "SelStart", Flags: 0x00004C03, Std: -1},       // 0x17
		{Name: "SelLength", Flags: 0x00004C03, Std: -1},      // 0x18
		{Name: "SelText", Flags: 0x00004C01, Std: -1},        // 0x19
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x1A
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x1B
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x1C
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x1D
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x1E
		{Name: "Style", Flags: 0x00E13406, Std: -1},          // 0x1F
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x20
		{Name: "ItemData", Flags: 0x00004D03, Std: -1},       // 0x21
		{Name: "NewIndex", Flags: 0x00003802, Std: -1},       // 0x22
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x23
		{Name: " ", Flags: 0xA0C11806, Std: 39},              // 0x24
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: -1},   // slot 0
		{Name: "Click", Params: 0, Std: -1},    // slot 1
		{Name: "DblClick", Params: 0, Std: -1}, // slot 2
		{Name: "DragDrop", Params: 3, Std: 2},  // slot 3
		{Name: "DragOver", Params: 4, Std: 3},  // slot 4
		{Name: "DropDown", Params: 0, Std: -1}, // slot 5
		{Name: "GotFocus", Params: 0, Std: 4},  // slot 6
		{Name: "KeyDown", Params: 2, Std: 5},   // slot 7
		{Name: "KeyPress", Params: 1, Std: 6},  // slot 8
		{Name: "KeyUp", Params: 2, Std: 7},     // slot 9
		{Name: "LostFocus", Params: 0, Std: 8}, // slot 10
	}},
	"Command": {DefCtlName: "Command", Props: []Prop{
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},        // 0x00
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x01
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x02
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x07
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x08
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x09
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0A
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0B
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x0C
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0D
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0E
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x0F
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x10
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x11
		{Name: "Value", Flags: 0x00002C04, Std: -1},          // 0x12
		{Name: "Default", Flags: 0x04C14404, Std: -1},        // 0x13
		{Name: "Cancel", Flags: 0x04C14404, Std: -1},         // 0x14
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x15
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x16
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x17
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x18
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x19
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x1A
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x1B
	}, Events: []Event{
		{Name: "Click", Params: 0, Std: -1},     // slot 0
		{Name: "DragDrop", Params: 3, Std: 2},   // slot 1
		{Name: "DragOver", Params: 4, Std: 3},   // slot 2
		{Name: "GotFocus", Params: 0, Std: 4},   // slot 3
		{Name: "KeyDown", Params: 2, Std: 5},    // slot 4
		{Name: "KeyPress", Params: 1, Std: 6},   // slot 5
		{Name: "KeyUp", Params: 2, Std: 7},      // slot 6
		{Name: "LostFocus", Params: 0, Std: 8},  // slot 7
		{Name: "MouseDown", Params: 4, Std: 9},  // slot 8
		{Name: "MouseMove", Params: 4, Std: 10}, // slot 9
		{Name: "MouseUp", Params: 4, Std: 11},   // slot 10
	}},
	"Data": {DefCtlName: "Data", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x01
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x02
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x03
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x04
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x05
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x06
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x07
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x08
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x09
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x0A
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0B
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0C
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x0D
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x0E
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x0F
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x10
		{Name: " ", Flags: 0x40011804, Std: -1},              // 0x11
		{Name: "Connect", Flags: 0x0001260D, Std: -1},        // 0x12
		{Name: "DatabaseName", Flags: 0x0011260D, Std: -1},   // 0x13
		{Name: "Database", Flags: 0x00005C71, Std: -1},       // 0x14
		{Name: "Recordset", Flags: 0x00005C72, Std: -1},      // 0x15
		{Name: "Exclusive", Flags: 0x00012604, Std: -1},      // 0x16
		{Name: "ReadOnly", Flags: 0x00012604, Std: -1},       // 0x17
		{Name: "RecordSource", Flags: 0x0011260D, Std: -1},   // 0x18
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},        // 0x19
		{Name: "EditMode", Flags: 0x00003802, Std: -1},       // 0x1A
		{Name: "Options", Flags: 0x00012602, Std: -1},        // 0x1B
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x1C
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x1D
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x1E
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x1F
	}, Events: []Event{
		{Name: "Error", Params: 2, Std: -1},      // slot 0
		{Name: "Reposition", Params: 0, Std: -1}, // slot 1
		{Name: "Validate", Params: 2, Std: -1},   // slot 2
		{Name: "DragDrop", Params: 3, Std: 2},    // slot 3
		{Name: "DragOver", Params: 4, Std: 3},    // slot 4
		{Name: "MouseDown", Params: 4, Std: 9},   // slot 5
		{Name: "MouseMove", Params: 4, Std: 10},  // slot 6
		{Name: "MouseUp", Params: 4, Std: 11},    // slot 7
	}},
	"Dir": {DefCtlName: "Dir", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x01
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x02
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x07
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x08
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x09
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0A
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x0B
		{Name: "Path", Flags: 0x00004C01, Std: -1},           // 0x0C
		{Name: "ListCount", Flags: 0x00005802, Std: -1},      // 0x0D
		{Name: "ListIndex", Flags: 0x00004C02, Std: -1},      // 0x0E
		{Name: "List", Flags: 0x00005901, Std: -1},           // 0x0F
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x10
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x11
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x12
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x13
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x14
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x15
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x16
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x17
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x18
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x19
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x1A
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x1B
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x1C
		{Name: " ", Flags: 0xA0C11806, Std: 39},              // 0x1D
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: -1},    // slot 0
		{Name: "Click", Params: 0, Std: -1},     // slot 1
		{Name: "DragDrop", Params: 3, Std: 2},   // slot 2
		{Name: "DragOver", Params: 4, Std: 3},   // slot 3
		{Name: "GotFocus", Params: 0, Std: 4},   // slot 4
		{Name: "KeyDown", Params: 2, Std: 5},    // slot 5
		{Name: "KeyPress", Params: 1, Std: 6},   // slot 6
		{Name: "KeyUp", Params: 2, Std: 7},      // slot 7
		{Name: "LostFocus", Params: 0, Std: 8},  // slot 8
		{Name: "MouseDown", Params: 4, Std: 9},  // slot 9
		{Name: "MouseMove", Params: 4, Std: 10}, // slot 10
		{Name: "MouseUp", Params: 4, Std: 11},   // slot 11
	}},
	"Drive": {DefCtlName: "Drive", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x01
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x02
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x07
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x08
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x09
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0A
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x0B
		{Name: "Drive", Flags: 0x00004C01, Std: -1},          // 0x0C
		{Name: "ListCount", Flags: 0x00005802, Std: -1},      // 0x0D
		{Name: "ListIndex", Flags: 0x00004C02, Std: -1},      // 0x0E
		{Name: "List", Flags: 0x00005901, Std: -1},           // 0x0F
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x10
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x11
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x12
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x13
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x14
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x15
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x16
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x17
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x18
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x19
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x1A
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x1B
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x1C
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: -1},   // slot 0
		{Name: "DragDrop", Params: 3, Std: 2},  // slot 1
		{Name: "DragOver", Params: 4, Std: 3},  // slot 2
		{Name: "GotFocus", Params: 0, Std: 4},  // slot 3
		{Name: "KeyDown", Params: 2, Std: 5},   // slot 4
		{Name: "KeyPress", Params: 1, Std: 6},  // slot 5
		{Name: "KeyUp", Params: 2, Std: 7},     // slot 6
		{Name: "LostFocus", Params: 0, Std: 8}, // slot 7
	}},
	"File": {DefCtlName: "File", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x01
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x02
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x07
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x08
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x09
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0A
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x0B
		{Name: "Path", Flags: 0x00002C01, Std: -1},           // 0x0C
		{Name: "Pattern", Flags: 0x00C12401, Std: -1},        // 0x0D
		{Name: "FileName", Flags: 0x00004C01, Std: -1},       // 0x0E
		{Name: "Normal", Flags: 0x00C12404, Std: -1},         // 0x0F
		{Name: "ReadOnly", Flags: 0x00C12404, Std: -1},       // 0x10
		{Name: "Archive", Flags: 0x00C12404, Std: -1},        // 0x11
		{Name: "Hidden", Flags: 0x00C12404, Std: -1},         // 0x12
		{Name: "System", Flags: 0x00C12404, Std: -1},         // 0x13
		{Name: "ListCount", Flags: 0x00005802, Std: -1},      // 0x14
		{Name: "ListIndex", Flags: 0x00004C02, Std: -1},      // 0x15
		{Name: "List", Flags: 0x00005901, Std: -1},           // 0x16
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x17
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x18
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x19
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x1A
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x1B
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x1C
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x1D
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x1E
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x1F
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x20
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x21
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x22
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x23
		{Name: "MultiSelect", Flags: 0x00E13206, Std: -1},    // 0x24
		{Name: "Selected", Flags: 0x00004D04, Std: -1},       // 0x25
		{Name: "TopIndex", Flags: 0x00004C02, Std: -1},       // 0x26
		{Name: " ", Flags: 0xA0C11806, Std: 39},              // 0x27
	}, Events: []Event{
		{Name: "Click", Params: 0, Std: -1},         // slot 0
		{Name: "DblClick", Params: 0, Std: -1},      // slot 1
		{Name: "DragDrop", Params: 3, Std: 2},       // slot 2
		{Name: "DragOver", Params: 4, Std: 3},       // slot 3
		{Name: "GotFocus", Params: 0, Std: 4},       // slot 4
		{Name: "KeyDown", Params: 2, Std: 5},        // slot 5
		{Name: "KeyPress", Params: 1, Std: 6},       // slot 6
		{Name: "KeyUp", Params: 2, Std: 7},          // slot 7
		{Name: "LostFocus", Params: 0, Std: 8},      // slot 8
		{Name: "MouseDown", Params: 4, Std: 9},      // slot 9
		{Name: "MouseMove", Params: 4, Std: 10},     // slot 10
		{Name: "MouseUp", Params: 4, Std: 11},       // slot 11
		{Name: "PathChange", Params: 0, Std: -1},    // slot 12
		{Name: "PatternChange", Params: 0, Std: -1}, // slot 13
	}},
	"Form": {DefCtlName: "Form", Props: []Prop{
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},         // 0x00
		{Name: "Name", Flags: 0x8600D43E, Std: 26},            // 0x01
		{Name: "hWnd", Flags: 0x80005802, Std: 2},             // 0x02
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},        // 0x03
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},        // 0x04
		{Name: "Left", Flags: 0x90022408, Std: 5},             // 0x05
		{Name: "Top", Flags: 0x9000240A, Std: 6},              // 0x06
		{Name: "Width", Flags: 0x90002409, Std: 7},            // 0x07
		{Name: "Height", Flags: 0x9000240B, Std: 8},           // 0x08
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},          // 0x09
		{Name: "WindowState", Flags: 0x00C14406, Std: -1},     // 0x0A
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},    // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},        // 0x0C
		{Name: "FontSize", Flags: 0x90104407, Std: 18},        // 0x0D
		{Name: "FontBold", Flags: 0x90004404, Std: 14},        // 0x0E
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},      // 0x0F
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16},  // 0x10
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},   // 0x11
		{Name: "hDC", Flags: 0x00005802, Std: -1},             // 0x12
		{Name: "CurrentX", Flags: 0x00004C07, Std: -1},        // 0x13
		{Name: "CurrentY", Flags: 0x00004C07, Std: -1},        // 0x14
		{Name: "ScaleLeft", Flags: 0x10404407, Std: -1},       // 0x15
		{Name: "ScaleTop", Flags: 0x10404407, Std: -1},        // 0x16
		{Name: "ScaleWidth", Flags: 0x10004407, Std: -1},      // 0x17
		{Name: "ScaleHeight", Flags: 0x10004407, Std: -1},     // 0x18
		{Name: "ScaleMode", Flags: 0x10422406, Std: -1},       // 0x19
		{Name: "FontTransparent", Flags: 0x10404404, Std: -1}, // 0x1A
		{Name: "DrawStyle", Flags: 0x00C14406, Std: -1},       // 0x1B
		{Name: "DrawWidth", Flags: 0x00C14402, Std: -1},       // 0x1C
		{Name: "FillStyle", Flags: 0x00C14406, Std: -1},       // 0x1D
		{Name: "FillColor", Flags: 0x00D12405, Std: -1},       // 0x1E
		{Name: "DrawMode", Flags: 0x00C14406, Std: -1},        // 0x1F
		{Name: "AutoRedraw", Flags: 0x10404404, Std: -1},      // 0x20
		{Name: "Picture", Flags: 0x04C1240C, Std: -1},         // 0x21
		{Name: "BorderStyle", Flags: 0x00E13206, Std: -1},     // 0x22
		{Name: "Icon", Flags: 0x00C1A60C, Std: -1},            // 0x23
		{Name: "LinkTopic", Flags: 0x00C1A401, Std: -1},       // 0x24
		{Name: "LinkMode", Flags: 0x00C12406, Std: -1},        // 0x25
		{Name: "MaxButton", Flags: 0x00E13204, Std: -1},       // 0x26
		{Name: "MinButton", Flags: 0x00E13204, Std: -1},       // 0x27
		{Name: "ControlBox", Flags: 0x00E13204, Std: -1},      // 0x28
		{Name: "Image", Flags: 0x0400580C, Std: -1},           // 0x29
		{Name: " ", Flags: 0x40011804, Std: -1},               // 0x2A
		{Name: " ", Flags: 0x40011804, Std: -1},               // 0x2B
		{Name: " ", Flags: 0x40011802, Std: -1},               // 0x2C
		{Name: " ", Flags: 0x40011802, Std: -1},               // 0x2D
		{Name: "Visible", Flags: 0x80C14404, Std: 10},         // 0x2E
		{Name: "Tag", Flags: 0x80C12201, Std: 25},             // 0x2F
		{Name: "MDIChild", Flags: 0x00E15404, Std: -1},        // 0x30
		{Name: "KeyPreview", Flags: 0x00C12204, Std: -1},      // 0x31
		{Name: "ClipControls", Flags: 0x80E13204, Std: 29},    // 0x32
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},   // 0x33
		{Name: "ActiveControl", Flags: 0x00005840, Std: -1},   // 0x34
		{Name: "ClientLeft", Flags: 0x02015808, Std: -1},      // 0x35
		{Name: "ClientTop", Flags: 0x0201580A, Std: -1},       // 0x36
		{Name: "ClientWidth", Flags: 0x02015808, Std: -1},     // 0x37
		{Name: "ClientHeight", Flags: 0x0201580A, Std: -1},    // 0x38
	}, Events: []Event{
		{Name: "DragDrop", Params: 3, Std: 2},     // slot 0
		{Name: "DragOver", Params: 4, Std: 3},     // slot 1
		{Name: "LinkClose", Params: 0, Std: -1},   // slot 2
		{Name: "LinkError", Params: 1, Std: -1},   // slot 3
		{Name: "LinkExecute", Params: 2, Std: -1}, // slot 4
		{Name: "LinkOpen", Params: 1, Std: -1},    // slot 5
		{Name: "Load", Params: 0, Std: -1},        // slot 6
		{Name: "Resize", Params: 0, Std: -1},      // slot 7
		{Name: "Unload", Params: 1, Std: -1},      // slot 8
		{Name: "QueryUnload", Params: 2, Std: -1}, // slot 9
		{Name: "Activate", Params: 0, Std: -1},    // slot 10
		{Name: "Deactivate", Params: 0, Std: -1},  // slot 11
		{Name: "Click", Params: 0, Std: 0},        // slot 12
		{Name: "DblClick", Params: 0, Std: 1},     // slot 13
		{Name: "GotFocus", Params: 0, Std: 4},     // slot 14
		{Name: "KeyDown", Params: 2, Std: 5},      // slot 15
		{Name: "KeyPress", Params: 1, Std: 6},     // slot 16
		{Name: "KeyUp", Params: 2, Std: 7},        // slot 17
		{Name: "LostFocus", Params: 0, Std: 8},    // slot 18
		{Name: "MouseDown", Params: 4, Std: 9},    // slot 19
		{Name: "MouseMove", Params: 4, Std: 10},   // slot 20
		{Name: "MouseUp", Params: 4, Std: 11},     // slot 21
		{Name: "Paint", Params: 0, Std: -1},       // slot 22
	}},
	"Frame": {DefCtlName: "Frame", Props: []Prop{
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},        // 0x00
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x01
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x02
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x03
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x04
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x05
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x06
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x07
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x08
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x09
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x0A
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0C
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x0D
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0E
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0F
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x10
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x11
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x12
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x13
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x14
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x15
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x16
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x17
		{Name: "ClipControls", Flags: 0x80E13204, Std: 29},   // 0x18
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x19
	}, Events: []Event{
		{Name: "DragDrop", Params: 3, Std: 2},   // slot 0
		{Name: "DragOver", Params: 4, Std: 3},   // slot 1
		{Name: "MouseDown", Params: 4, Std: 9},  // slot 2
		{Name: "MouseMove", Params: 4, Std: 10}, // slot 3
		{Name: "MouseUp", Params: 4, Std: 11},   // slot 4
		{Name: "Click", Params: 0, Std: 0},      // slot 5
		{Name: "DblClick", Params: 0, Std: 1},   // slot 6
	}},
	"HScroll": {DefCtlName: "HScroll", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},           // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},          // 0x01
		{Name: "Left", Flags: 0x90022408, Std: 5},           // 0x02
		{Name: "Top", Flags: 0x9000240A, Std: 6},            // 0x03
		{Name: "Width", Flags: 0x90002409, Std: 7},          // 0x04
		{Name: "Height", Flags: 0x9000240B, Std: 8},         // 0x05
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},        // 0x06
		{Name: "Visible", Flags: 0x80C14404, Std: 10},       // 0x07
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},  // 0x08
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},      // 0x09
		{Name: "Min", Flags: 0x00C12402, Std: -1},           // 0x0A
		{Name: "Max", Flags: 0x00C12402, Std: -1},           // 0x0B
		{Name: "SmallChange", Flags: 0x00C12402, Std: -1},   // 0x0C
		{Name: "LargeChange", Flags: 0x00C12402, Std: -1},   // 0x0D
		{Name: "Value", Flags: 0x00412402, Std: -1},         // 0x0E
		{Name: "Parent", Flags: 0x8000583F, Std: 20},        // 0x0F
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},      // 0x10
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},      // 0x11
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},       // 0x12
		{Name: "Tag", Flags: 0x80C12201, Std: 25},           // 0x13
		{Name: "hWnd", Flags: 0x80005802, Std: 2},           // 0x14
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31}, // 0x15
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: -1},   // slot 0
		{Name: "DragDrop", Params: 3, Std: 2},  // slot 1
		{Name: "DragOver", Params: 4, Std: 3},  // slot 2
		{Name: "GotFocus", Params: 0, Std: 4},  // slot 3
		{Name: "KeyDown", Params: 2, Std: 5},   // slot 4
		{Name: "KeyPress", Params: 1, Std: 6},  // slot 5
		{Name: "KeyUp", Params: 2, Std: 7},     // slot 6
		{Name: "LostFocus", Params: 0, Std: 8}, // slot 7
		{Name: "Scroll", Params: 0, Std: -1},   // slot 8
	}},
	"Image": {DefCtlName: "Image", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},          // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},         // 0x01
		{Name: "Picture", Flags: 0x04C1260C, Std: -1},      // 0x02
		{Name: "Left", Flags: 0x90022408, Std: 5},          // 0x03
		{Name: "Top", Flags: 0x9000240A, Std: 6},           // 0x04
		{Name: "Width", Flags: 0x90002409, Std: 7},         // 0x05
		{Name: "Height", Flags: 0x9000240B, Std: 8},        // 0x06
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},       // 0x07
		{Name: "Visible", Flags: 0x80C14404, Std: 10},      // 0x08
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11}, // 0x09
		{Name: "Stretch", Flags: 0x00C12604, Std: -1},      // 0x0A
		{Name: "Parent", Flags: 0x8000583F, Std: 20},       // 0x0B
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},     // 0x0C
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},     // 0x0D
		{Name: "Tag", Flags: 0x80C12201, Std: 25},          // 0x0E
		{Name: "BorderStyle", Flags: 0x00C12406, Std: -1},  // 0x0F
		{Name: "DataSource", Flags: 0x82D13201, Std: 40},   // 0x10
		{Name: "DataField", Flags: 0x80D12601, Std: 41},    // 0x11
		{Name: "DataChanged", Flags: 0x80102A04, Std: 42},  // 0x12
	}, Events: []Event{
		{Name: "Click", Params: 0, Std: 0},      // slot 0
		{Name: "DblClick", Params: 0, Std: 1},   // slot 1
		{Name: "DragDrop", Params: 3, Std: 2},   // slot 2
		{Name: "DragOver", Params: 4, Std: 3},   // slot 3
		{Name: "MouseDown", Params: 4, Std: 9},  // slot 4
		{Name: "MouseMove", Params: 4, Std: 10}, // slot 5
		{Name: "MouseUp", Params: 4, Std: 11},   // slot 6
	}},
	"Label": {DefCtlName: "Label", Props: []Prop{
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},        // 0x00
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x01
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x02
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x03
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x04
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x05
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x06
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x07
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x08
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x09
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x0A
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0C
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x0D
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0E
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0F
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x10
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x11
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x12
		{Name: "BorderStyle", Flags: 0x00C12406, Std: -1},    // 0x13
		{Name: "Alignment", Flags: 0x01C12286, Std: -1},      // 0x14
		{Name: "LinkTopic", Flags: 0x80C1A401, Std: 34},      // 0x15
		{Name: "LinkItem", Flags: 0x80C1A401, Std: 33},       // 0x16
		{Name: "LinkMode", Flags: 0x80C1A406, Std: 32},       // 0x17
		{Name: "AutoSize", Flags: 0x00C12604, Std: -1},       // 0x18
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x19
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x1A
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x1B
		{Name: "LinkTimeout", Flags: 0x80C12202, Std: 35},    // 0x1C
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x1D
		{Name: "WordWrap", Flags: 0x00C12404, Std: -1},       // 0x1E
		{Name: "BackStyle", Flags: 0x00C12406, Std: -1},      // 0x1F
		{Name: "DataSource", Flags: 0x82D13201, Std: 40},     // 0x20
		{Name: "DataField", Flags: 0x80D12601, Std: 41},      // 0x21
		{Name: "DataChanged", Flags: 0x80102A04, Std: 42},    // 0x22
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: 16},     // slot 0
		{Name: "Click", Params: 0, Std: 0},       // slot 1
		{Name: "DblClick", Params: 0, Std: 1},    // slot 2
		{Name: "DragDrop", Params: 3, Std: 2},    // slot 3
		{Name: "DragOver", Params: 4, Std: 3},    // slot 4
		{Name: "LinkClose", Params: 0, Std: 14},  // slot 5
		{Name: "LinkError", Params: 1, Std: 12},  // slot 6
		{Name: "LinkOpen", Params: 1, Std: 13},   // slot 7
		{Name: "MouseDown", Params: 4, Std: 9},   // slot 8
		{Name: "MouseMove", Params: 4, Std: 10},  // slot 9
		{Name: "MouseUp", Params: 4, Std: 11},    // slot 10
		{Name: "LinkNotify", Params: 0, Std: 15}, // slot 11
	}},
	"Line": {DefCtlName: "Line", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},         // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},        // 0x01
		{Name: "BorderColor", Flags: 0x81D12285, Std: -1}, // 0x02
		{Name: "X1", Flags: 0x00014408, Std: -1},          // 0x03
		{Name: "Y1", Flags: 0x0001440A, Std: -1},          // 0x04
		{Name: "X2", Flags: 0x00014408, Std: -1},          // 0x05
		{Name: "Y2", Flags: 0x0001440A, Std: -1},          // 0x06
		{Name: "Visible", Flags: 0x80C14404, Std: 10},     // 0x07
		{Name: "Parent", Flags: 0x8000583F, Std: 20},      // 0x08
		{Name: "Tag", Flags: 0x80C12201, Std: 25},         // 0x09
		{Name: "DrawMode", Flags: 0x00C14406, Std: -1},    // 0x0A
		{Name: "BorderStyle", Flags: 0x01C12286, Std: -1}, // 0x0B
		{Name: "BorderWidth", Flags: 0x00C12402, Std: -1}, // 0x0C
	}, Events: []Event{}},
	"List": {DefCtlName: "List", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x01
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x02
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x07
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x08
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x09
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0A
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0B
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x0C
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0D
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0E
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x0F
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x10
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x11
		{Name: "ListCount", Flags: 0x00005802, Std: -1},      // 0x12
		{Name: "ListIndex", Flags: 0x00004C02, Std: -1},      // 0x13
		{Name: "List", Flags: 0x00004D01, Std: -1},           // 0x14
		{Name: "Sorted", Flags: 0x00E13204, Std: -1},         // 0x15
		{Name: "Text", Flags: 0x00005801, Std: -1},           // 0x16
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x17
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x18
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x19
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x1A
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x1B
		{Name: "Columns", Flags: 0x00E12402, Std: -1},        // 0x1C
		{Name: "MultiSelect", Flags: 0x00E13206, Std: -1},    // 0x1D
		{Name: "Selected", Flags: 0x00004D04, Std: -1},       // 0x1E
		{Name: "SelCount", Flags: 0x00005802, Std: -1},       // 0x1F
		{Name: "TopIndex", Flags: 0x00004C02, Std: -1},       // 0x20
		{Name: "ItemData", Flags: 0x00004D03, Std: -1},       // 0x21
		{Name: "NewIndex", Flags: 0x00003802, Std: -1},       // 0x22
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x23
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x24
		{Name: " ", Flags: 0xA0C11806, Std: 39},              // 0x25
	}, Events: []Event{
		{Name: "Click", Params: 0, Std: -1},     // slot 0
		{Name: "DblClick", Params: 0, Std: -1},  // slot 1
		{Name: "DragDrop", Params: 3, Std: 2},   // slot 2
		{Name: "DragOver", Params: 4, Std: 3},   // slot 3
		{Name: "GotFocus", Params: 0, Std: 4},   // slot 4
		{Name: "KeyDown", Params: 2, Std: 5},    // slot 5
		{Name: "KeyPress", Params: 1, Std: 6},   // slot 6
		{Name: "KeyUp", Params: 2, Std: 7},      // slot 7
		{Name: "LostFocus", Params: 0, Std: 8},  // slot 8
		{Name: "MouseDown", Params: 4, Std: 9},  // slot 9
		{Name: "MouseMove", Params: 4, Std: 10}, // slot 10
		{Name: "MouseUp", Params: 4, Std: 11},   // slot 11
	}},
	"MDIForm": {DefCtlName: "MDIForm", Props: []Prop{
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},       // 0x00
		{Name: "Name", Flags: 0x8600D43E, Std: 26},          // 0x01
		{Name: "hWnd", Flags: 0x80005802, Std: 2},           // 0x02
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x03
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x04
		{Name: "Left", Flags: 0x90022408, Std: 5},           // 0x05
		{Name: "Top", Flags: 0x9000240A, Std: 6},            // 0x06
		{Name: "Width", Flags: 0x90002409, Std: 7},          // 0x07
		{Name: "Height", Flags: 0x9000240B, Std: 8},         // 0x08
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},        // 0x09
		{Name: "WindowState", Flags: 0x00C14406, Std: -1},   // 0x0A
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},  // 0x0B
		{Name: "ScrollBars", Flags: 0x00E13204, Std: -1},    // 0x0C
		{Name: "ActiveForm", Flags: 0x0000583F, Std: -1},    // 0x0D
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x0E
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x0F
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x10
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x11
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x12
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x13
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x14
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x15
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x16
		{Name: "ScaleWidth", Flags: 0x00005807, Std: -1},    // 0x17
		{Name: "ScaleHeight", Flags: 0x00005807, Std: -1},   // 0x18
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x19
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x1A
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x1B
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x1C
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x1D
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x1E
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x1F
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x20
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x21
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x22
		{Name: "Icon", Flags: 0x00C1A60C, Std: -1},          // 0x23
		{Name: "LinkTopic", Flags: 0x00C1A401, Std: -1},     // 0x24
		{Name: "LinkMode", Flags: 0x00C12406, Std: -1},      // 0x25
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x26
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x27
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x28
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x29
		{Name: " ", Flags: 0x40011804, Std: -1},             // 0x2A
		{Name: " ", Flags: 0x40011804, Std: -1},             // 0x2B
		{Name: " ", Flags: 0x40011802, Std: -1},             // 0x2C
		{Name: " ", Flags: 0x40011802, Std: -1},             // 0x2D
		{Name: "Visible", Flags: 0x80C14404, Std: 10},       // 0x2E
		{Name: "Tag", Flags: 0x80C12201, Std: 25},           // 0x2F
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x30
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x31
		{Name: " ", Flags: 0x40000804, Std: 30},             // 0x32
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31}, // 0x33
		{Name: "ActiveControl", Flags: 0x00005840, Std: -1}, // 0x34
		{Name: "ClientLeft", Flags: 0x02015808, Std: -1},    // 0x35
		{Name: "ClientTop", Flags: 0x0201580A, Std: -1},     // 0x36
		{Name: "ClientWidth", Flags: 0x02015808, Std: -1},   // 0x37
		{Name: "ClientHeight", Flags: 0x0201580A, Std: -1},  // 0x38
	}, Events: []Event{
		{Name: "DragDrop", Params: 3, Std: 2},     // slot 0
		{Name: "DragOver", Params: 4, Std: 3},     // slot 1
		{Name: "LinkClose", Params: 0, Std: -1},   // slot 2
		{Name: "LinkError", Params: 1, Std: -1},   // slot 3
		{Name: "LinkExecute", Params: 2, Std: -1}, // slot 4
		{Name: "LinkOpen", Params: 1, Std: -1},    // slot 5
		{Name: "Load", Params: 0, Std: -1},        // slot 6
		{Name: "Resize", Params: 0, Std: -1},      // slot 7
		{Name: "Unload", Params: 1, Std: -1},      // slot 8
		{Name: "QueryUnload", Params: 2, Std: -1}, // slot 9
		{Name: "Activate", Params: 0, Std: -1},    // slot 10
		{Name: "Deactivate", Params: 0, Std: -1},  // slot 11
	}},
	"Menu": {DefCtlName: "Menu", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},           // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},          // 0x01
		{Name: "Visible", Flags: 0x00C12404, Std: -1},       // 0x02
		{Name: "Caption", Flags: 0x0041A601, Std: -1},       // 0x03
		{Name: "Checked", Flags: 0x00C12404, Std: -1},       // 0x04
		{Name: "Enabled", Flags: 0x00C12404, Std: -1},       // 0x05
		{Name: " ", Flags: 0x00C12C04, Std: -1},             // 0x06
		{Name: " ", Flags: 0x00C13A04, Std: -1},             // 0x07
		{Name: "Shortcut", Flags: 0x02C5B202, Std: -1},      // 0x08
		{Name: "Parent", Flags: 0x8000583F, Std: 20},        // 0x09
		{Name: "Tag", Flags: 0x80C12201, Std: 25},           // 0x0A
		{Name: "WindowList", Flags: 0x00C13404, Std: -1},    // 0x0B
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31}, // 0x0C
	}, Events: []Event{
		{Name: "Click", Params: 0, Std: -1}, // slot 0
	}},
	"Option": {DefCtlName: "Option", Props: []Prop{
		{Name: "Caption", Flags: 0x80CA4401, Std: 12},        // 0x00
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x01
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x02
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x03
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x04
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x05
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x06
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x07
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x08
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x09
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x0A
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0C
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x0D
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0E
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0F
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x10
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x11
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x12
		{Name: "Value", Flags: 0x00C14404, Std: -1},          // 0x13
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x14
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x15
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x16
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x17
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x18
		{Name: "Alignment", Flags: 0x00E13406, Std: -1},      // 0x19
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x1A
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x1B
	}, Events: []Event{
		{Name: "Click", Params: 0, Std: -1},     // slot 0
		{Name: "DblClick", Params: 0, Std: -1},  // slot 1
		{Name: "DragDrop", Params: 3, Std: 2},   // slot 2
		{Name: "DragOver", Params: 4, Std: 3},   // slot 3
		{Name: "GotFocus", Params: 0, Std: 4},   // slot 4
		{Name: "KeyDown", Params: 2, Std: 5},    // slot 5
		{Name: "KeyPress", Params: 1, Std: 6},   // slot 6
		{Name: "KeyUp", Params: 2, Std: 7},      // slot 7
		{Name: "LostFocus", Params: 0, Std: 8},  // slot 8
		{Name: "MouseDown", Params: 4, Std: 9},  // slot 9
		{Name: "MouseMove", Params: 4, Std: 10}, // slot 10
		{Name: "MouseUp", Params: 4, Std: 11},   // slot 11
	}},
	"Picture": {DefCtlName: "Picture", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},             // 0x00
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},        // 0x01
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},            // 0x02
		{Name: "Picture", Flags: 0x04C1240C, Std: -1},         // 0x03
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},        // 0x04
		{Name: "Left", Flags: 0x90022408, Std: 5},             // 0x05
		{Name: "Top", Flags: 0x9000240A, Std: 6},              // 0x06
		{Name: "Width", Flags: 0x90002409, Std: 7},            // 0x07
		{Name: "Height", Flags: 0x9000240B, Std: 8},           // 0x08
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},          // 0x09
		{Name: "Visible", Flags: 0x80C14404, Std: 10},         // 0x0A
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},    // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},        // 0x0C
		{Name: "FontSize", Flags: 0x90104407, Std: 18},        // 0x0D
		{Name: "FontBold", Flags: 0x90004404, Std: 14},        // 0x0E
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},      // 0x0F
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16},  // 0x10
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},   // 0x11
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},        // 0x12
		{Name: "hDC", Flags: 0x00005802, Std: -1},             // 0x13
		{Name: "CurrentX", Flags: 0x00004C07, Std: -1},        // 0x14
		{Name: "CurrentY", Flags: 0x00004C07, Std: -1},        // 0x15
		{Name: "ScaleLeft", Flags: 0x10404407, Std: -1},       // 0x16
		{Name: "ScaleTop", Flags: 0x10404407, Std: -1},        // 0x17
		{Name: "ScaleWidth", Flags: 0x10004407, Std: -1},      // 0x18
		{Name: "ScaleHeight", Flags: 0x10004407, Std: -1},     // 0x19
		{Name: "ScaleMode", Flags: 0x10422406, Std: -1},       // 0x1A
		{Name: "FontTransparent", Flags: 0x10404404, Std: -1}, // 0x1B
		{Name: "DrawStyle", Flags: 0x00C14406, Std: -1},       // 0x1C
		{Name: "DrawWidth", Flags: 0x00C14402, Std: -1},       // 0x1D
		{Name: "FillStyle", Flags: 0x00C14406, Std: -1},       // 0x1E
		{Name: "FillColor", Flags: 0x00D12405, Std: -1},       // 0x1F
		{Name: "DrawMode", Flags: 0x00C14406, Std: -1},        // 0x20
		{Name: "AutoRedraw", Flags: 0x10404404, Std: -1},      // 0x21
		{Name: " ", Flags: 0x40000804, Std: 30},               // 0x22
		{Name: "AutoSize", Flags: 0x00C12604, Std: -1},        // 0x23
		{Name: "BorderStyle", Flags: 0x80C14406, Std: 28},     // 0x24
		{Name: "LinkTopic", Flags: 0x80C1A401, Std: 34},       // 0x25
		{Name: "LinkItem", Flags: 0x80C1A401, Std: 33},        // 0x26
		{Name: "LinkMode", Flags: 0x80C1A406, Std: 32},        // 0x27
		{Name: "Image", Flags: 0x0400580C, Std: -1},           // 0x28
		{Name: "Parent", Flags: 0x8000583F, Std: 20},          // 0x29
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},        // 0x2A
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},        // 0x2B
		{Name: "LinkTimeout", Flags: 0x80C12202, Std: 35},     // 0x2C
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},         // 0x2D
		{Name: "Tag", Flags: 0x80C12201, Std: 25},             // 0x2E
		{Name: "hWnd", Flags: 0x80005802, Std: 2},             // 0x2F
		{Name: "ClipControls", Flags: 0x80E13204, Std: 29},    // 0x30
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},   // 0x31
		{Name: "Align", Flags: 0x80C12406, Std: 38},           // 0x32
		{Name: " ", Flags: 0xA0C11806, Std: 39},               // 0x33
		{Name: "DataSource", Flags: 0x82D13201, Std: 40},      // 0x34
		{Name: "DataField", Flags: 0x80D12601, Std: 41},       // 0x35
		{Name: "DataChanged", Flags: 0x80102A04, Std: 42},     // 0x36
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: 16},     // slot 0
		{Name: "Click", Params: 0, Std: 0},       // slot 1
		{Name: "DblClick", Params: 0, Std: 1},    // slot 2
		{Name: "DragDrop", Params: 3, Std: 2},    // slot 3
		{Name: "DragOver", Params: 4, Std: 3},    // slot 4
		{Name: "GotFocus", Params: 0, Std: 4},    // slot 5
		{Name: "KeyDown", Params: 2, Std: 5},     // slot 6
		{Name: "KeyPress", Params: 1, Std: 6},    // slot 7
		{Name: "KeyUp", Params: 2, Std: 7},       // slot 8
		{Name: "LinkClose", Params: 0, Std: 14},  // slot 9
		{Name: "LinkError", Params: 1, Std: 12},  // slot 10
		{Name: "LinkOpen", Params: 1, Std: 13},   // slot 11
		{Name: "LostFocus", Params: 0, Std: 8},   // slot 12
		{Name: "MouseDown", Params: 4, Std: 9},   // slot 13
		{Name: "MouseMove", Params: 4, Std: 10},  // slot 14
		{Name: "MouseUp", Params: 4, Std: 11},    // slot 15
		{Name: "Paint", Params: 0, Std: -1},      // slot 16
		{Name: "LinkNotify", Params: 0, Std: 15}, // slot 17
		{Name: "Resize", Params: 0, Std: -1},     // slot 18
	}},
	"Shape": {DefCtlName: "Shape", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},         // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},        // 0x01
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},    // 0x02
		{Name: "BorderColor", Flags: 0x81D12285, Std: -1}, // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},         // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},          // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},        // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},       // 0x07
		{Name: "Visible", Flags: 0x80C14404, Std: 10},     // 0x08
		{Name: "Parent", Flags: 0x8000583F, Std: 20},      // 0x09
		{Name: "Tag", Flags: 0x80C12201, Std: 25},         // 0x0A
		{Name: "Shape", Flags: 0x01C12286, Std: -1},       // 0x0B
		{Name: "DrawMode", Flags: 0x00C14406, Std: -1},    // 0x0C
		{Name: "BorderStyle", Flags: 0x00C12486, Std: -1}, // 0x0D
		{Name: "BorderWidth", Flags: 0x00C12482, Std: -1}, // 0x0E
		{Name: "FillColor", Flags: 0x00D12485, Std: -1},   // 0x0F
		{Name: "BackStyle", Flags: 0x01C12286, Std: -1},   // 0x10
		{Name: "FillStyle", Flags: 0x01C12286, Std: -1},   // 0x11
	}, Events: []Event{}},
	"Text": {DefCtlName: "Text", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},            // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},           // 0x01
		{Name: "BackColor", Flags: 0x80D12605, Std: 3},       // 0x02
		{Name: "ForeColor", Flags: 0x80D12405, Std: 4},       // 0x03
		{Name: "Left", Flags: 0x90022408, Std: 5},            // 0x04
		{Name: "Top", Flags: 0x9000240A, Std: 6},             // 0x05
		{Name: "Width", Flags: 0x90002409, Std: 7},           // 0x06
		{Name: "Height", Flags: 0x9000240B, Std: 8},          // 0x07
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},         // 0x08
		{Name: "Visible", Flags: 0x80C14404, Std: 10},        // 0x09
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},   // 0x0A
		{Name: "Text", Flags: 0x80CA4401, Std: 27},           // 0x0B
		{Name: "FontName", Flags: 0x90024401, Std: 13},       // 0x0C
		{Name: "FontSize", Flags: 0x90104407, Std: 18},       // 0x0D
		{Name: "FontBold", Flags: 0x90004404, Std: 14},       // 0x0E
		{Name: "FontItalic", Flags: 0x90004404, Std: 15},     // 0x0F
		{Name: "FontStrikethru", Flags: 0x90004404, Std: 16}, // 0x10
		{Name: "FontUnderline", Flags: 0x90004404, Std: 17},  // 0x11
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},       // 0x12
		{Name: "BorderStyle", Flags: 0x00E13406, Std: -1},    // 0x13
		{Name: "LinkTopic", Flags: 0x80C1A401, Std: 34},      // 0x14
		{Name: "LinkItem", Flags: 0x80C1A401, Std: 33},       // 0x15
		{Name: "LinkMode", Flags: 0x80C1A406, Std: 32},       // 0x16
		{Name: "MultiLine", Flags: 0x00E13404, Std: -1},      // 0x17
		{Name: "ScrollBars", Flags: 0x00E13406, Std: -1},     // 0x18
		{Name: "SelStart", Flags: 0x00004C03, Std: -1},       // 0x19
		{Name: "SelLength", Flags: 0x00004C03, Std: -1},      // 0x1A
		{Name: "SelText", Flags: 0x00004C01, Std: -1},        // 0x1B
		{Name: "Parent", Flags: 0x8000583F, Std: 20},         // 0x1C
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},       // 0x1D
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},       // 0x1E
		{Name: "LinkTimeout", Flags: 0x80C12202, Std: 35},    // 0x1F
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},        // 0x20
		{Name: "Tag", Flags: 0x80C12201, Std: 25},            // 0x21
		{Name: "PasswordChar", Flags: 0x00C92401, Std: -1},   // 0x22
		{Name: "HideSelection", Flags: 0x00E13204, Std: -1},  // 0x23
		{Name: "Alignment", Flags: 0x00E13406, Std: -1},      // 0x24
		{Name: "MaxLength", Flags: 0x00C12403, Std: -1},      // 0x25
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31},  // 0x26
		{Name: "hWnd", Flags: 0x80005802, Std: 2},            // 0x27
		{Name: " ", Flags: 0xA0C11806, Std: 39},              // 0x28
		{Name: "DataSource", Flags: 0x82D13201, Std: 40},     // 0x29
		{Name: "DataField", Flags: 0x80D12601, Std: 41},      // 0x2A
		{Name: "DataChanged", Flags: 0x80102A04, Std: 42},    // 0x2B
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: 16},     // slot 0
		{Name: "DragDrop", Params: 3, Std: 2},    // slot 1
		{Name: "DragOver", Params: 4, Std: 3},    // slot 2
		{Name: "GotFocus", Params: 0, Std: 4},    // slot 3
		{Name: "KeyDown", Params: 2, Std: 5},     // slot 4
		{Name: "KeyPress", Params: 1, Std: 6},    // slot 5
		{Name: "KeyUp", Params: 2, Std: 7},       // slot 6
		{Name: "LinkClose", Params: 0, Std: 14},  // slot 7
		{Name: "LinkError", Params: 1, Std: 12},  // slot 8
		{Name: "LinkOpen", Params: 1, Std: 13},   // slot 9
		{Name: "LostFocus", Params: 0, Std: 8},   // slot 10
		{Name: "LinkNotify", Params: 0, Std: 15}, // slot 11
		{Name: "MouseDown", Params: 4, Std: 9},   // slot 12
		{Name: "MouseMove", Params: 4, Std: 10},  // slot 13
		{Name: "MouseUp", Params: 4, Std: 11},    // slot 14
		{Name: "Click", Params: 0, Std: 0},       // slot 15
		{Name: "DblClick", Params: 0, Std: 1},    // slot 16
	}},
	"Timer": {DefCtlName: "Timer", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},      // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},     // 0x01
		{Name: "Enabled", Flags: 0x00C12604, Std: -1},  // 0x02
		{Name: "Interval", Flags: 0x00C12403, Std: -1}, // 0x03
		{Name: "Parent", Flags: 0x8000583F, Std: 20},   // 0x04
		{Name: "Tag", Flags: 0x80C12201, Std: 25},      // 0x05
		{Name: " ", Flags: 0x40020803, Std: -1},        // 0x06
		{Name: "Left", Flags: 0x82013408, Std: 36},     // 0x07
		{Name: "Top", Flags: 0x8201340A, Std: 37},      // 0x08
	}, Events: []Event{
		{Name: "Timer", Params: 0, Std: -1}, // slot 0
	}},
	"VScroll": {DefCtlName: "VScroll", Props: []Prop{
		{Name: "Name", Flags: 0x8600D43E, Std: 0},           // 0x00
		{Name: "Index", Flags: 0x84C1D43D, Std: 1},          // 0x01
		{Name: "Left", Flags: 0x90022408, Std: 5},           // 0x02
		{Name: "Top", Flags: 0x9000240A, Std: 6},            // 0x03
		{Name: "Width", Flags: 0x90002409, Std: 7},          // 0x04
		{Name: "Height", Flags: 0x9000240B, Std: 8},         // 0x05
		{Name: "Enabled", Flags: 0x80C14404, Std: 9},        // 0x06
		{Name: "Visible", Flags: 0x80C14404, Std: 10},       // 0x07
		{Name: "MousePointer", Flags: 0x80C12406, Std: 11},  // 0x08
		{Name: "TabIndex", Flags: 0x84014402, Std: 19},      // 0x09
		{Name: "Min", Flags: 0x00C12402, Std: -1},           // 0x0A
		{Name: "Max", Flags: 0x00C12402, Std: -1},           // 0x0B
		{Name: "SmallChange", Flags: 0x00C12402, Std: -1},   // 0x0C
		{Name: "LargeChange", Flags: 0x00C12402, Std: -1},   // 0x0D
		{Name: "Value", Flags: 0x00412402, Std: -1},         // 0x0E
		{Name: "Parent", Flags: 0x8000583F, Std: 20},        // 0x0F
		{Name: "DragMode", Flags: 0x80C12206, Std: 21},      // 0x10
		{Name: "DragIcon", Flags: 0x84C1A20C, Std: 22},      // 0x11
		{Name: "TabStop", Flags: 0x80C14404, Std: 24},       // 0x12
		{Name: "Tag", Flags: 0x80C12201, Std: 25},           // 0x13
		{Name: "hWnd", Flags: 0x80005802, Std: 2},           // 0x14
		{Name: "HelpContextID", Flags: 0x80C12203, Std: 31}, // 0x15
	}, Events: []Event{
		{Name: "Change", Params: 0, Std: -1},   // slot 0
		{Name: "DragDrop", Params: 3, Std: 2},  // slot 1
		{Name: "DragOver", Params: 4, Std: 3},  // slot 2
		{Name: "GotFocus", Params: 0, Std: 4},  // slot 3
		{Name: "KeyDown", Params: 2, Std: 5},   // slot 4
		{Name: "KeyPress", Params: 1, Std: 6},  // slot 5
		{Name: "KeyUp", Params: 2, Std: 7},     // slot 6
		{Name: "LostFocus", Params: 0, Std: 8}, // slot 7
		{Name: "Scroll", Params: 0, Std: -1},   // slot 8
	}},
}
